import { Suspense } from "react";
import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";

const STEPS = [
  {
    title: "Upload a PDF invoice",
    body: "Go to Upload and drag-and-drop or select a PDF. Integris accepts invoices from any ERP or accounting system.",
  },
  {
    title: "OCR and AI extraction",
    body: "The system runs OCR to extract text, then uses AI to parse invoice fields (seller, buyer, line items, totals, VAT). This usually takes under 30 seconds.",
  },
  {
    title: "Human review",
    body: "Every document goes through a review step before it can be submitted. Open the document, verify the extracted fields against the PDF, correct any errors, and click Approve.",
  },
  {
    title: "FA(3) XML generation",
    body: "After approval, Integris generates a KSeF-compliant FA(3) XML file deterministically from the approved data. The AI is never used for this step.",
  },
  {
    title: "KSeF submission",
    body: "The XML is submitted to KSeF. Integris polls for the official UPO receipt and updates the document status. You can download the UPO from the audit trail.",
  },
];

const FAQS = [
  {
    q: "Can AI be wrong?",
    a: "Yes. OCR and AI extraction can produce errors, especially on scanned or low-quality PDFs. Always review extracted fields before approving.",
  },
  {
    q: "What happens if KSeF rejects the invoice?",
    a: "The document moves to the rejected status. You can correct the extracted data and retry submission from the review screen.",
  },
  {
    q: "Is the FA(3) XML generated by AI?",
    a: "No. XML is generated by a deterministic algorithm from approved structured data. AI is only used for text extraction, never for the final XML.",
  },
  {
    q: "Which KSeF environment is active?",
    a: "This is controlled by your server configuration (KSEF_ENV). Contact your administrator to confirm whether you are in dry-run, sandbox, or production mode.",
  },
];

export default function HelpPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Suspense>
        <AppHeader />
      </Suspense>

      <main className="mx-auto max-w-2xl px-6 py-12">
        <div className="mb-6">
          <Link href="/dashboard" className="text-sm text-gray-500 hover:underline">
            ← Back to dashboard
          </Link>
        </div>

        <h1 className="mb-8 text-xl font-semibold text-gray-900">Help</h1>

        {/* Workflow */}
        <section className="mb-10">
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-gray-400">
            How it works
          </h2>
          <ol className="space-y-4">
            {STEPS.map((step, i) => (
              <li key={i} className="flex gap-4 rounded-xl border border-gray-200 bg-white p-5">
                <span className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-blue-600 text-xs font-bold text-white">
                  {i + 1}
                </span>
                <div>
                  <p className="text-sm font-semibold text-gray-900">{step.title}</p>
                  <p className="mt-1 text-sm text-gray-500">{step.body}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>

        {/* FAQ */}
        <section className="mb-10">
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-gray-400">
            Frequently asked questions
          </h2>
          <div className="space-y-4">
            {FAQS.map((faq, i) => (
              <div key={i} className="rounded-xl border border-gray-200 bg-white p-5">
                <p className="text-sm font-semibold text-gray-900">{faq.q}</p>
                <p className="mt-1 text-sm text-gray-500">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Contact */}
        <section>
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-gray-400">
            Contact
          </h2>
          <div className="rounded-xl border border-gray-200 bg-white p-5">
            <p className="text-sm text-gray-500">
              For technical issues or questions, contact your Integris administrator or reach us at{" "}
              <a
                href="mailto:support@integris.pl"
                className="font-medium text-blue-600 hover:underline"
              >
                support@integris.pl
              </a>
              .
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
